### ISSUE TITLE
Data persistent for life time in post, put or delete req

### ISSUE THREAD

**Issue by whoafridi** [kitloong/json-server-vercel#8]
is the updated data saved in the `db.json` JSON file for life time like if I can't delete data? I found so many blogs that don't save data for life time . it's automatically deleted after some time. So, there is anyother way to do that?

**Comment by kitloong** [comment]
Hi @whoafridi, I am sorry for the delay.

If you've managed to execute a `POST` or `DELETE` request, the data should have been saved in the `db.json` file. However, please note that we are deploying the `db.json` file alongside the source code to Vercel. This means that with each deployment, the previous version of your `db.json` will be overwritten.

To make your `db.json` persistent across deployments I think you may look into Vercel's file storage solution.

Hope this can help you.

**Comment by nicopcat** [comment]
I think json server is a temporary data base emulator, originally used in dev enviroment. If you want to save data permanently, you should connect to a real database like MongoDB or MySQL, etc.

**Comment by kitloong** [comment]
Hi @nicopcat 

Yes you are right. 

I believe this issue is for the use case where the dev team wish to test the write operation before the api is in place.

However, by allowing write into db.json also allowed ANYONE update your json file.

**Therefore, anyone using this feature should be aware of the potential security implications and consider their own policies accordingly.**
